### ISSUE TITLE
Question about some if statements

### ISSUE THREAD

**Issue by nichbar** [niharika2810/ToastHandler#1]
Nice article, but I have a small question about the implementation.

Isn't these if statements bypass Android 7.1 (SDK 25) ?

https://github.com/niharika2810/ToastHandler/blob/471bc5ad1dbcd4ba93a257dd442e4eee266ce6e0/toasthandler/src/main/java/com/toastfix/toastcompatwrapper/ToastHandler.kt#L25

https://github.com/niharika2810/ToastHandler/blob/471bc5ad1dbcd4ba93a257dd442e4eee266ce6e0/toasthandler/src/main/java/com/toastfix/toastcompatwrapper/ToastHandler.kt#L40

**Comment by niharika2810** [comment]
My bad!! Thanks for pointing this out. It equals to Android 25 here. I was trying something and then changed it. Pushed the code.
