### ISSUE TITLE
Decerease minSdkVersion for better compatibility

### ISSUE THREAD

**Issue by nichbar** [niharika2810/ToastHandler#2]
Since this library does not actually require 19 as the minimum Android SDK version, how about decrease it to a proper value?

https://github.com/niharika2810/ToastHandler/blob/471bc5ad1dbcd4ba93a257dd442e4eee266ce6e0/toasthandler/build.gradle#L28

**Comment by niharika2810** [comment]
yeah sure.Will do this right away.

**Comment by niharika2810** [comment]
This is just set in the sample app only. Anyone using it can change it accordingly.

**Comment by niharika2810** [comment]
yeah sure.doing it right away,
