### ISSUE TITLE
Kotlin Extension Function for easier usability.

### ISSUE THREAD

**Issue by gogeta95** [niharika2810/ToastHandler#7]
Library can make use of kotlin extension functions to make it easier to use.

current usage: 
```kotlin
ToastHandler.showToast(this, "Hello,I am Toast", Toast.LENGTH_LONG)
```

proposed usage:
`showToast` as an Extension function of `Context`

```kotlin
showToast("Hi,I am Toast", Toast.LENGTH_LONG)
```

**Comment by niharika2810** [comment]
Hey, Yeah on the way for next release. Good suggestion. Thank you!! 👍🏻

**Comment by gogeta95** [comment]
can i open a PR for the same?

**Comment by niharika2810** [comment]
Oh, I already did the change yesterday. I didn't know this :-) Do you want me to merge yours?

**Comment by gogeta95** [comment]
oh, in that case it is fine. you can go ahead.
